version: '3.8'
services:
  db:
    image: mysql:8.0.19
    container_name: mysql-cont
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
    networks:
      - 'photo-network'
    ports:
      - '3306:3306'
    volumes:
      - '/Users/mac/IdeaProjects/spring-boot-demo/src/main/resources/db/:/docker-entrypoint-initdb.d'
  backend:
    build:
      context: '/Users/mac/IdeaProjects/spring-boot-demo'
      dockerfile: 'Dockerfile'
    image: 'springboot-img:v0.1'
    container_name: springboot-cont
    restart:
      on-failure:5
    networks:
      - 'photo-network'
    depends_on:
      - db
    ports:
      - '8080:8080'
  frontend:
    build:
      context: '/Users/mac/IdeaProjects/Photos'
      dockerfile: 'Dockerfile'
    image: 'react-img:v0.1'
    container_name: react-cont
    networks:
      - 'photo-network'
    ports:
      - '3000:3000'
    stdin_open: true
volumes:
  mysqlvol:
networks:
  photo-network: {}